[env]
CGO_CFLAGS_ALLOW = "-Xpreprocessor"
ENVIRONMENT = "development"
UPLOAD_PATH = "./data/uploads"
LEVELDB_PATH = "./data/db"

[tools]
dprint = "0.47.2"
watchexec = "2.1.2"
go = "1.23.1"
node = "22"
"go:honnef.co/go/tools/cmd/staticcheck" = "0.6.0-0.dev"

[tasks."setup"]
description = "Setup the project"
run = ["mise install", "go mod download", "go mod tidy", "cd js && npm install"]
sources = ["go.mod", ".mise.toml", "*/**/*.go"]
outputs = ["go.sum"]

[tasks."dev"]
description = "Run the server and watch for changes"
run = "mise watch -t serve -r"

[tasks."serve"]
description = "Run the server"
run = "go run ./cmd/server"
sources = ["go.mod", "*/**/*.go"]

[tasks."format"]
description = "Format files in the project"
run = "dprint fmt"

[tasks."check:format"]
description = "Check formatting"
run = "dprint check"

[tasks."check:lint"]
description = "Check linting"
run = ["staticcheck ./...", "cd js && npm run check:types"]

[tasks."test:unit"]
description = "Run unit tests"
run = ["go test ./... -short", "cd js && npm run test -- run"]

[tasks."build:js"]
description = "Build the JS bundle"
run = "cd js && npm run build"

[tasks."default"]
hide = true
depends = ["dev"]

[settings]
activate_aggressive = true
experimental = true
yes = true
